/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppHistoriqueRouteImport } from './routes/_app.historique'
import { Route as AppProjetsRouteImport } from './routes/_app.projets'
import { Route as AppRapportsRouteImport } from './routes/_app.rapports'
import { Route as AppRessourcesRouteImport } from './routes/_app.ressources'
import { Route as AppUtilisateursRouteImport } from './routes/_app.utilisateurs'
import { Route as AppProjetsIdRouteImport } from './routes/_app.projets.$id'
import { Route as AppProjetsNewRouteImport } from './routes/_app.projets.new'
import { Route as AppProjetsIdEditRouteImport } from './routes/_app.projets.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoriqueRoute = AppHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetsRoute = AppProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => AppRoute,
} as any)
const AppRapportsRoute = AppRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AppRoute,
} as any)
const AppRessourcesRoute = AppRessourcesRouteImport.update({
  id: '/ressources',
  path: '/ressources',
  getParentRoute: () => AppRoute,
} as any)
const AppUtilisateursRoute = AppUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetsIdRoute = AppProjetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjetsRoute,
} as any)
const AppProjetsNewRoute = AppProjetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppProjetsRoute,
} as any)
const AppProjetsIdEditRoute = AppProjetsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppProjetsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/historique': typeof AppHistoriqueRoute
  '/projets': typeof AppProjetsRouteWithChildren
  '/rapports': typeof AppRapportsRoute
  '/ressources': typeof AppRessourcesRoute
  '/utilisateurs': typeof AppUtilisateursRoute
  '/projets/$id': typeof AppProjetsIdRouteWithChildren
  '/projets/new': typeof AppProjetsNewRoute
  '/projets/$id/edit': typeof AppProjetsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/historique': typeof AppHistoriqueRoute
  '/projets': typeof AppProjetsRouteWithChildren
  '/rapports': typeof AppRapportsRoute
  '/ressources': typeof AppRessourcesRoute
  '/utilisateurs': typeof AppUtilisateursRoute
  '/projets/$id': typeof AppProjetsIdRouteWithChildren
  '/projets/new': typeof AppProjetsNewRoute
  '/projets/$id/edit': typeof AppProjetsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/historique': typeof AppHistoriqueRoute
  '/_app/projets': typeof AppProjetsRouteWithChildren
  '/_app/rapports': typeof AppRapportsRoute
  '/_app/ressources': typeof AppRessourcesRoute
  '/_app/utilisateurs': typeof AppUtilisateursRoute
  '/_app/projets/$id': typeof AppProjetsIdRouteWithChildren
  '/_app/projets/new': typeof AppProjetsNewRoute
  '/_app/projets/$id/edit': typeof AppProjetsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/historique'
    | '/projets'
    | '/rapports'
    | '/ressources'
    | '/utilisateurs'
    | '/projets/$id'
    | '/projets/new'
    | '/projets/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/historique'
    | '/projets'
    | '/rapports'
    | '/ressources'
    | '/utilisateurs'
    | '/projets/$id'
    | '/projets/new'
    | '/projets/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/historique'
    | '/_app/projets'
    | '/_app/rapports'
    | '/_app/ressources'
    | '/_app/utilisateurs'
    | '/_app/projets/$id'
    | '/_app/projets/new'
    | '/_app/projets/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historique': {
      id: '/_app/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof AppHistoriqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projets': {
      id: '/_app/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof AppProjetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rapports': {
      id: '/_app/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof AppRapportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ressources': {
      id: '/_app/ressources'
      path: '/ressources'
      fullPath: '/ressources'
      preLoaderRoute: typeof AppRessourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/utilisateurs': {
      id: '/_app/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof AppUtilisateursRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projets/$id': {
      id: '/_app/projets/$id'
      path: '/$id'
      fullPath: '/projets/$id'
      preLoaderRoute: typeof AppProjetsIdRouteImport
      parentRoute: typeof AppProjetsRoute
    }
    '/_app/projets/new': {
      id: '/_app/projets/new'
      path: '/new'
      fullPath: '/projets/new'
      preLoaderRoute: typeof AppProjetsNewRouteImport
      parentRoute: typeof AppProjetsRoute
    }
    '/_app/projets/$id/edit': {
      id: '/_app/projets/$id/edit'
      path: '/edit'
      fullPath: '/projets/$id/edit'
      preLoaderRoute: typeof AppProjetsIdEditRouteImport
      parentRoute: typeof AppProjetsIdRoute
    }
  }
}

interface AppProjetsIdRouteChildren {
  AppProjetsIdEditRoute: typeof AppProjetsIdEditRoute
}

const AppProjetsIdRouteChildren: AppProjetsIdRouteChildren = {
  AppProjetsIdEditRoute: AppProjetsIdEditRoute,
}

const AppProjetsIdRouteWithChildren = AppProjetsIdRoute._addFileChildren(
  AppProjetsIdRouteChildren,
)

interface AppProjetsRouteChildren {
  AppProjetsIdRoute: typeof AppProjetsIdRouteWithChildren
  AppProjetsNewRoute: typeof AppProjetsNewRoute
}

const AppProjetsRouteChildren: AppProjetsRouteChildren = {
  AppProjetsIdRoute: AppProjetsIdRouteWithChildren,
  AppProjetsNewRoute: AppProjetsNewRoute,
}

const AppProjetsRouteWithChildren = AppProjetsRoute._addFileChildren(
  AppProjetsRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoriqueRoute: typeof AppHistoriqueRoute
  AppProjetsRoute: typeof AppProjetsRouteWithChildren
  AppRapportsRoute: typeof AppRapportsRoute
  AppRessourcesRoute: typeof AppRessourcesRoute
  AppUtilisateursRoute: typeof AppUtilisateursRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppHistoriqueRoute: AppHistoriqueRoute,
  AppProjetsRoute: AppProjetsRouteWithChildren,
  AppRapportsRoute: AppRapportsRoute,
  AppRessourcesRoute: AppRessourcesRoute,
  AppUtilisateursRoute: AppUtilisateursRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
